//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FmsAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalBatch
    {
        public int BatchID { get; set; }
        public string BatchName { get; set; }
        public System.DateTime PurchasedDate { get; set; }
        public string Purpose { get; set; }
    }
}
