//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FmsAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed_Inventory
    {
        public int FeedID { get; set; }
        public Nullable<int> FeedTypeID { get; set; }
        public Nullable<decimal> StockQuantity { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
