//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FmsAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdLookupValue
    {
        public int IdValueID { get; set; }
        public Nullable<int> IdLookupID { get; set; }
        public string ValueName { get; set; }
    }
}
