//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FmsAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int ProductionID { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> AnimalID { get; set; }
    }
}
